#cloud-config
runcmd:
  - [curl, -fsSL, "https://raw.githubusercontent.com/solusio/applications/master/n8n/setup", -o, "/root/setup.sh"]
  - [chmod, +x, "/root/setup.sh"]
  - /bin/bash /root/setup.sh 2>&1 | while IFS= read -r line; do printf "%s %s\n" "$(date)" "$line"; done >> /var/log/n8n-install.log
  - rm -f /root/setup.sh
