#cloud-config
write_files:
  - path: /root/setup.sh
    permissions: '0755'
    content: |
      #!/bin/bash
      HOSTNAME={{ hostname }}
      match=$(echo "${HOSTNAME}" | grep -oP '^(?!\-)(?:[a-zA-Z\d\-]{0,62}[a-zA-Z\d]\.){1,126}(?!\d+)[a-zA-Z\d]{1,63}$')
      if [ -z "$match" ]; then
        hostnamectl set-hostname "${HOSTNAME}.local.domain"
        HOSTNAME="${HOSTNAME}.local.domain"
      fi
      setenforce 0
      /usr/local/cpanel/bin/set_hostname "${HOSTNAME}"
      /usr/local/cpanel/cpkeyclt
runcmd:
  - sh /root/setup.sh
  - rm -f /root/setup.sh
